const fs = require("fs");
const p = "d:/CINSIDE/frontend/electron/main.cjs";
let lines = fs.readFileSync(p, "utf8").split("\n");
const insertAt = 1025;
const newLines = [
  "  // === ??????????????? ===",
  "  if (!isDev) {",
  "    autoUpdater.autoDownload = false;",
  "    autoUpdater.autoInstallOnAppQuit = true;",
  "",
  "    autoUpdater.on(\"update-available\", (info) => {",
  "      debugLog(`[updater] update available: ${info.version}`);",
  "      if (mainWindow && !mainWindow.isDestroyed()) {",
  "        mainWindow.webContents.send(\"update-available\", info);",
  "      }",
  "    });",
  "    autoUpdater.on(\"update-not-available\", (info) => {",
  "      debugLog(`[updater] update not available`);",
  "      if (mainWindow && !mainWindow.isDestroyed()) {",
  "        mainWindow.webContents.send(\"update-not-available\", info);",
  "      }",
  "    });",
  "    autoUpdater.on(\"download-progress\", (progress) => {",
  "      if (mainWindow && !mainWindow.isDestroyed()) {",
  "        mainWindow.webContents.send(\"update-download-progress\", progress);",
  "      }",
  "    });",
  "    autoUpdater.on(\"update-downloaded\", (info) => {",
  "      debugLog(`[updater] update downloaded: ${info.version}`);",
  "      if (mainWindow && !mainWindow.isDestroyed()) {",
  "        mainWindow.webContents.send(\"update-downloaded\", info);",
  "      }",
  "    });",
  "    autoUpdater.on(\"error\", (err) => {",
  "      debugLog(`[updater] error: ${err.message}`);",
  "      if (mainWindow && !mainWindow.isDestroyed()) {",
  "        mainWindow.webContents.send(\"update-error\", { message: err.message });",
  "      }",
  "    });",
  "",
  "    // ??3??????",
  "    setTimeout(() => {",
  "      autoUpdater.checkForUpdates().catch((e) => {",
  "        debugLog(`[updater] check failed: ${e.message}`);",
  "      });",
  "    }, 3000);",
  "  }",
  "",
];
lines.splice(insertAt, 0, ...newLines);
fs.writeFileSync(p, lines.join("\n"));
console.log("Step 2 done");
